
 development:
  adapter: sqlite3
  database: amigo_secreto_development
  host: localhost
  username: root
  password: 
  pool: 5
  timeout: 5000
  

test:
  adapter: sqlite3
  database: amigo_secreto_test
  host: localhost
  username: root
  password: 
  pool: 5
  timeout: 5000

