source 'http://rubygems.org'

gem 'rails', '3.2.8'

gem 'bootstrap-sass', '~> 3.3.1'
gem 'sass-rails', '>= 3.2' 
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'    
gem 'jbuilder', '~> 1.0.1'
gem 'protected_attributes'
gem 'bootswatch-rails'


# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

group :development, :test do 
  gem 'sqlite3'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
  gem 'unicorn' # make sure you follow installation instructions for this gem
  #gem 'rails_log_stdout',           github: 'heroku/rails_log_stdout'
  #gem 'rails3_serve_static_assets', github: 'heroku/rails3_serve_static_assets'  
end


group :doc do
  gem 'sdoc', require: false
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
